app/models.py
from app import db
from flask_login import UserMixin
from app import login_manager
from werkzeug.security import generate_password_hash, check_password_hash


@login_manager.user_loader
def load_user(user_id):
  return User.query.get(int(user_id))

class User(UserMixin, db.Model):
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(120), nullable=False)
  email = db.Column(db.String(120), nullable=False)
  password = db.Column(db.String(100), nullable=False)
  post = db.relationship('Post', backref='user', lazy=True)

  def set_password(self, password):
    self.password = generate_password_hash(password)

  def check_password(self, pass_key):
    return check_password_hash(self.password, pass_key)
  
  def __repr__(self):
    return f'User {self.id} {self.name} {self.email} {self.password}'

class Post(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  content = db.Column(db.Text, nullable=False)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

  def __repr__(self):
    return f'Post => id: {self.user_id}, content: {self.content}'

app/__init__.py
from flask import Flask
from app.config import config
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'

def create_app(config_name='development'):
  app = Flask(__name__)
  app.config.from_object(config[config_name])

  db.init_app(app)
  login_manager.init_app(app)

  from app.main.routes import main
  from app.auth.routes import auth
  from app.user.routes import user
  from app.posts.routes import posts

  app.register_blueprint(main)
  app.register_blueprint(auth, url_prefix='/auth')
  app.register_blueprint(user, url_prefix='/altonero')
  app.register_blueprint(posts, url_prefix='/altonero')

  return app

app/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__) 

@main.route('/', methods=['GET'])
def index():
  return render_template('index.html')

app/posts/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required
from flask_login import current_user
from app.models import Post
from .form import PostForm
from app import db

posts = Blueprint('posts', __name__)

@posts.route('/', methods=['GET'])
@login_required
def index():
  postform = PostForm()
  return render_template('posts.html', postform=postform)

@posts.route('/create', methods=['POST'])
def create():
  postform = PostForm()
  if request.method == 'POST' and postform.validate_on_submit():
    post = Post(content=postform.content.data, user=current_user)
    db.session.add(post)
    db.session.commit()
    flash('Tweep posted')
    postform.content.data = ''
    return redirect(url_for('posts.index'))
  return redirect(url_for('posts.index'))

app/user/routes.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from app.models import Post

user = Blueprint('user', __name__)

@user.route('/<username>')
@login_required
def profile(username):
  user_posts = Post.query.filter_by(user=current_user).order_by(Post.id.desc())
  return render_template('profile.html',username=username, user_posts=user_posts)

app/templates/index.html
{% extends 'layout.html' %}

{% block content %}
  <span>home</span>
  <div>
    <a href={{ url_for('auth.login') }}>Login</a>
    <a href={{ url_for('auth.new') }}>Signup</a>
  </div>
{% endblock content%}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <div>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul>
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
  </div>
  {% block content %} {% endblock content %}
</body>
</html>

app/templates/login.html
{% extends 'layout.html' %}

{% block content %}
<div>
  <li><a href={{ url_for('main.index')}}>Home</a></li>
</div>
  <span>This is login page</span>
  <div>
    <form method='POST' action='/auth/session'>
      {{ loginform.csrf_token }}
      {{ loginform.email(placeholder='email') }}
        {% if  loginform.email.errors %}
          {% for error in loginform.email.errors %}
            {{ error }}
          {% endfor %}
        {% endif %}
      {{ loginform.password(placeholder='password') }}
      {{ loginform.submit }}
    </form>
  </div>
{% endblock %}

app/templates/macro.html
{% macro login_user_nav() %}
  <div>
    <ul>
      <li><a href={{ url_for('auth.logout') }}>Logout</a></li>
    </ul>
  </div>
{% endmacro%}

app/templates/posts.html
{% extends 'layout.html' %}
{% from 'macro.html' import login_user_nav %}
{% block content %}
  <div>
    {{login_user_nav() }}
  </div>
  <span>posts page</span>
  <form method='POST' action='/altonero/create'>
    {{ postform.csrf_token }}
    {{ postform.content(placeholder='What is on your mind?') }}
    {{ postform.submit }}
  </form>
  <p> <a href={{ url_for('user.profile', username=current_user.name)}}>profile page</a></p>
{% endblock %}

app/templates/profile.html
{% extends 'layout.html' %}
{% from 'macro.html' import login_user_nav %}
{% block content %}
 {% if current_user.is_authenticated %}
   {{ login_user_nav() }}
   {{ current_user.name }}
 {% endif %}
 <p><a href={{ url_for('posts.index') }}>tweep</a></p>
 <hr>
 {% if user_posts %}
    {% for post in user_posts %}
      <ul>
        <li>{{ post.content }}</li>
      </ul>
    {% endfor %}
 {% endif %}
{% endblock content %}

app/templates/signup.html
{% extends 'layout.html' %}

{% block content %}
  <span>sign up</span>
  <form method="Post" action="/auth/signup">
    {{ form.csrf_token }}
    {{ form.name(placeholder='name') }}
     {% if form.name.errors %}
       <ul>
         {% for error in form.name.errors %}
           <li>{{ error }}</li>
         {% endfor %}
       </ul>
     {% endif %}
    {{ form.email(placeholder='email') }}
      {% if form.email.errors %}
        <ul>
          {% for error in form.email.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {{ form.password(placeholder='password') }}
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    {{ form.confirm_password(placeholder='confirm password') }}
      {% if form.confirm_password.errors %}
        {% for error in form.confirm_password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    {{ form.submit }}
  </form>
  <div> 
    <a href={{ url_for('main.index') }}>home</a>
  </div>
{% endblock %}